### ISSUE TITLE
Allow for default Send From address

### ISSUE THREAD

**Issue by AndyM48** [zacky48/check-before-sending-email#4]
Similar request to #2 

I have several email accounts and find that I sometimes send emails from the wrong account. Would it be possible to either:

1. Create a Send From whitelist, similar to the Destination whitelist, so that the check does not occur if the Send From address matches.
or
2. Restrict the check to only occur for certain accounts  

Thank you

**Comment by zacky48** [comment]
Thank you for your feature suggestion.

>Create a Send From whitelist, similar to the Destination whitelist, so that the check does not occur if the Send From address matches.

We have implemented this feature in version 0.3.1.
Kindly verify it at your convenience.

**Comment by AndyM48** [comment]
Thank you very much for your prompt reply. The mod works very well, except that:

If there is nothing to check, and Send Later is not required, then the Check Before Sending Email window still appears and Send Now still has to be selected.

**Comment by zacky48** [comment]
Thank you for your confirmation.

If I understand correctly, you would like the email to be sent without displaying the pre-send confirmation screen when there are no items to check and the “Send Later” option is not required.

**Comment by AndyM48** [comment]
Exactly so.

Thank you.

**Comment by zacky48** [comment]
In version 0.3.2, we added a feature that skips the confirmation screen when no check items exist.

To enable this feature, please check “Do not display the confirmation screen if there are no check items.” in the settings screen.

Thank you.

**Comment by AndyM48** [comment]
Great, thank you very much.

**Comment by AndyM48** [comment]
I am getting this error on sending a second unchecked email:

`Unable to check this email because other pre-send checks are in progress.`

The first email, with nothing to check, went fine.

**Comment by zacky48** [comment]
@AndyM48 

Thank you for checking.
We apologize for the inconvenience.

The bug you pointed out has been fixed in version 0.3.3.

**Comment by AndyM48** [comment]
Thank you very much
